set(PCEM_PRIVATE_API ${PCEM_PRIVATE_API}
        ${CMAKE_SOURCE_DIR}/includes/private/video/video.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_et4000.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_et4000w32.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_genius.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_hercules.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_ht216.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_icd2061.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_ics2595.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_im1024.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_incolor.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_mda.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_mga.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_olivetti_m24.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_oti037.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_oti067.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_paradise.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_pc1512.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_pc1640.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_pc200.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_pcjr.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_pgc.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_ps1_svga.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_quadcolor.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_s3.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_s3_virge.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_sdac_ramdac.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_sigma.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_stg_ramdac.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_svga.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_svga_render.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_svga_render_remap.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_t1000.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_t3100e.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_tandy.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_tandysl.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_tgui9440.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_tkd8001_ramdac.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_tvga.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_tvp3026_ramdac.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_unk_ramdac.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_vga.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_voodoo_banshee_blitter.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_voodoo_banshee.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_voodoo_blitter.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_voodoo_codegen_x86-64.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_voodoo_codegen_x86.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_voodoo_common.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_voodoo_display.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_voodoo_dither.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_voodoo_fb.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_voodoo_fifo.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_voodoo.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_voodoo_reg.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_voodoo_regs.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_voodoo_render.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_voodoo_setup.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_voodoo_texture.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_wy700.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_ati18800.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_ati28800.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_ati68860_ramdac.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_ati_eeprom.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_ati_mach64.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_cga.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_cl5429.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_colorplus.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_compaq_cga.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_ddc.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_ega.h
        ${CMAKE_SOURCE_DIR}/includes/private/video/vid_v6355.h
        )

if(USE_EXPERIMENTAL AND USE_EXPERIMENTAL_PGC)
        set(PCEM_DEFINES ${PCEM_DEFINES} USE_EXPERIMENTAL_PGC)
endif()

set(PCEM_SRC ${PCEM_SRC}
        video/vid_ati18800.cpp
        video/vid_ati28800.cpp
        video/vid_ati68860_ramdac.cpp
        video/vid_ati_eeprom.cpp
        video/vid_ati_mach64.cpp
        video/vid_cga.cpp
        video/vid_cl5429.cpp
        video/vid_colorplus.cpp
        video/vid_compaq_cga.cpp
        video/vid_ddc.cpp
        video/vid_ega.cpp
        video/vid_et4000.cpp
        video/vid_et4000w32.cpp
        video/vid_genius.cpp
        video/vid_hercules.cpp
        video/vid_ht216.cpp
        video/vid_icd2061.cpp
        video/vid_ics2595.cpp
        video/vid_im1024.cpp
        video/vid_incolor.cpp
        video/vid_mda.cpp
        video/vid_mga.cpp
        video/vid_olivetti_m24.cpp
        video/vid_oti037.cpp
        video/vid_oti067.cpp
        video/vid_paradise.cpp
        video/vid_pc1512.cpp
        video/vid_pc1640.cpp
        video/vid_pc200.cpp
        video/vid_pcjr.cpp
        video/vid_pgc.cpp
        video/vid_ps1_svga.cpp
        video/vid_quadcolor.cpp
        video/vid_s3.cpp
        video/vid_s3_virge.cpp
        video/vid_sdac_ramdac.cpp
        video/vid_sigma.cpp
        video/vid_stg_ramdac.cpp
        video/vid_svga.cpp
        video/vid_svga_render.cpp
        video/vid_t1000.cpp
        video/vid_t3100e.cpp
        video/vid_tandy.cpp
        video/vid_tandysl.cpp
        video/vid_tgui9440.cpp
        video/vid_tkd8001_ramdac.cpp
        video/vid_tvga.cpp
        video/vid_tvp3026_ramdac.cpp
        video/vid_unk_ramdac.cpp
        video/vid_v6355.cpp
        video/vid_vga.cpp
        video/vid_voodoo.cpp
        video/vid_voodoo_banshee.cpp
        video/vid_voodoo_banshee_blitter.cpp
        video/vid_voodoo_blitter.cpp
        video/vid_voodoo_display.cpp
        video/vid_voodoo_fb.cpp
        video/vid_voodoo_fifo.cpp
        video/vid_voodoo_reg.cpp
        video/vid_voodoo_render.cpp
        video/vid_voodoo_setup.cpp
        video/vid_voodoo_texture.cpp
        video/vid_wy700.cpp
        video/video.cpp
        )
