set(PCEM_PRIVATE_API ${PCEM_PRIVATE_API}
        ${CMAKE_SOURCE_DIR}/includes/private/models/82091aa.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/acc2036.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/acc2168.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/acc3221.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/acer386sx.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/ali1429.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/amstrad.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/cbm_io.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/cmd640.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/compaq.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/cs8230.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/dells200.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/dma.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/grid.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/headland.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/i430fx.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/i430hx.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/i430lx.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/i430vx.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/i440bx.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/i440fx.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/intel.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/jim.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/laserxt.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/model.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/mvp3.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/neat.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/nmi.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/olivetti_m24.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/opti495.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/pc87306.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/pc87307.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/pic.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/piix.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/piix_pm.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/pit.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/ps1.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/ps2.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/ps2_mca.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/scat.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/serial.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/sio.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/sl82c460.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/superxt.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/t1000.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/t3100e.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/um8669f.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/um8881f.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/vl82c480.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/vt82c586b.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/w83877tf.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/w83977tf.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/wd76c10.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/xi8088.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/zenith.h
        )

set(PCEM_SRC ${PCEM_SRC}
        models/82091aa.cpp
        models/acc2036.cpp
        models/acc2168.cpp
        models/acc3221.cpp
        models/acer386sx.cpp
        models/ali1429.cpp
        models/amstrad.cpp
        models/cbm_io.cpp
        models/cmd640.cpp
        models/compaq.cpp
        models/cs8230.cpp
        models/dells200.cpp
        models/dma.cpp
        models/grid.cpp
        models/headland.cpp
        models/i430fx.cpp
        models/i430hx.cpp
        models/i430lx.cpp
        models/i430vx.cpp
        models/i440bx.cpp
        models/i440fx.cpp
        models/intel.cpp
        models/jim.cpp
        models/laserxt.cpp
        models/model.cpp
        models/mvp3.cpp
        models/neat.cpp
        models/nmi.cpp
        models/nvr_tc8521.cpp
        models/olivetti_m24.cpp
        models/opti495.cpp
        models/pc87306.cpp
        models/pc87307.cpp
        models/pic.cpp
        models/piix.cpp
        models/piix_pm.cpp
        models/pit.cpp
        models/ps1.cpp
        models/ps2.cpp
        models/ps2_mca.cpp
        models/scamp.cpp
        models/scat.cpp
        models/serial.cpp
        models/sio.cpp
        models/sl82c460.cpp
        models/superxt.cpp
        models/t1000.cpp
        models/t3100e.cpp
        models/um8669f.cpp
        models/um8881f.cpp
        models/vl82c480.cpp
        models/vt82c586b.cpp
        models/w83877tf.cpp
        models/w83977tf.cpp
        models/wd76c10.cpp
        models/xi8088.cpp
        models/zenith.cpp
        )